### ISSUE TITLE
Set charset header in json responses

### ISSUE THREAD

**Issue by ben** [raylu/pigwig#1]
It'd be nice if pigwig would by default encode output as utf-8, and set the header that lets the client know that.

**Comment by raylu** [comment]
Out of curiosity, why did this come up?

**Comment by ben** [comment]
Trying to query a service using `requests` inside a Docker container. I think it's because `LANG` isn't set, so `requests` doesn't set a charset on the request, so PigWig doesn't respond with one.

**Comment by raylu** [comment]
e8b0b5fee84dda6e7f0d6717fdc79e5d1a02c21d is in 0.3 now
